### ISSUE TITLE
Typo in section 5

### ISSUE THREAD

**Issue by hobbsy** [sirredbeard/Awesome-WSL#21]
small typo in section 5

https://github.com/sirredbeard/Awesome-WSL#5-wsl2

"users can try WSL2 using Hypver-V"

*Hyper-V

**Comment by sirredbeard** [comment]
Why don't you submit a PR so you can have a commit credit on the project? 🙂

**Comment by hobbsy** [comment]
I don't know how to do that - but will Google as I want to learn how to contribute to Github projects this year.

Is flagging a typo helpful or a nuisance?

**Comment by hobbsy** [comment]
Thanks for the encouragement. I've attempted a Pull Request - but I'm not sure if I've done it right?

**Comment by sirredbeard** [comment]
PR merged.

**Comment by hobbsy** [comment]
Can I now delete the fork from my Github profile ?

eg.
https://github.com/hobbsy/Awesome-WSL

"Delete this repository"

or does it need to stay ?

**Comment by sirredbeard** [comment]
You can delete it!
