### ISSUE TITLE
Is there no Awesome-WSL projects/guides related to audio you'd suggest?

### ISSUE THREAD

**Issue by TryTryAgain** [sirredbeard/Awesome-WSL#42]
I've seen a few blog posts, and I know even x410, which you list, has [the post](https://x410.dev/cookbook/wsl/enabling-sound-in-wsl-ubuntu-let-it-sing/) about how to get it working. When I found the Awesome-WSL listing I was excited hoping to find some wrappers/utils/projects related to audio devices for WSL. Maybe the pulse audio workaround is it for now and there's been no further development in that space... Thought I'd raise the issue to see.

**Comment by sirredbeard** [comment]
Pulse Audio is it for now but audio support is coming as part of official GUI support in a few months.
