### ISSUE TITLE
Xming is actually updated monthly

### ISSUE THREAD

**Issue by gIsForGravity** [sirredbeard/Awesome-WSL#45]
Xming is updated monthly, but you have to pay money for it. If you give the author a donation above a certain amount, you get a year's worth of downloads.

**Comment by crramirez** [comment]
I hope that they package their app to Microsoft Store. I tried once to donate, and it was so tricky that I turned back and discovered X410.

**Comment by sirredbeard** [comment]
You are welcome to submit a PR that clarifies this. Thank you.
