### ISSUE TITLE
Link to Castle-Winbuntu broken

### ISSUE THREAD

**Issue by strarsis** [sirredbeard/Awesome-WSL#57]
The link to `Castle-Winbuntu` points to https://github.com/rodtreweek/Castle-Winbuntu, a repo which doesn't exist (anymore).

**Comment by sirredbeard** [comment]
Why don't you submit a PR to fix it?

**Comment by pea-sys** [comment]
It is fixed in the following commit

b7a7260f4ad034517d14d636ca3d7fbb9ac2429a

**Comment by strarsis** [comment]
@sirredbeard: Sorry, I lost sight of that issue.
