### ISSUE TITLE
Could you give a reason why suggest X410 at first class? Or it would looks like an advertisement.

### ISSUE THREAD

**Issue by eromoe** [sirredbeard/Awesome-WSL#6]
FAQ #9

> X servers for Windows include X410 💰 ($5 but very highly recommended), VcXsrv, or Xming on Windows 10 .

I think you should include the reason.

**Comment by sirredbeard** [comment]
That's a good idea. I will update that.

It's because it's actively updated and the developers are very responsive.

**Comment by rwilliams** [comment]
I've been using VcXsrv, x410 seems to hang a lot.
