### ISSUE TITLE
wallpaper

### ISSUE THREAD

**Issue by anantgupta129** [sirredbeard/Awesome-WSL#73]
hi @sirredbeard 
can you share your background image

**Comment by sirredbeard** [comment]
![2148281](https://user-images.githubusercontent.com/33820650/150007874-1411e0b7-f376-43ad-a6d5-430e64ca0e39.jpg)

It's the default wallpaper from openSUSE Tumbleweed.

**Comment by anantgupta129** [comment]
thanks @sirredbeard

**Comment by Geezus42** [comment]
https://en.opensuse.org/openSUSE:Wallpapers

https://github.com/openSUSE/artwork/tree/archival/Wallpapers
