### ISSUE TITLE
about  KVM   on WSL 2 -- is  Stable Windows 10 (21H2) or Insider  version 

### ISSUE THREAD

**Issue by CMingTseng** [sirredbeard/Awesome-WSL#78]
Dear Sir

thx  your post 

but 

i try it  can not work !!!??

maybe " you use  Insider Fast Ring, tested on build 19645.1 " ?

i use  stable  Windows10 21H2 --the KVM can not work !!

and i  ref this https://github.com/microsoft/WSL/issues/4193

maybe  WSL2 with KVM at windows 10  must use Insider  version ?

THX

**Comment by sirredbeard** [comment]
I replied to your e-mail.
